PREFIX foaf: <https://xmls.com/foaf/0.1/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX ex: <http://example.org/vocabulary/> 
PREFIX ex2: <https://example.org/resource/> 

# All rooms which are located in the Zlatá Nemocnice hospital
SELECT ?room WHERE {
    ex2:hos1 a ex:Hospital ;
        ex:name "Zlatá Nemocnice"@cs .
    ?room a ex:Room ;
        ex:location ex2:hos1 .
}